name: Webapp CI/CD pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build backend docker image
        run: docker build -t hristijanalachoski/webapp-backend ./backend
      - name: Pushing docker image to Docker Hub
        run: docker push hristijanalachoski/webapp-backend
  build-frontend:
    name: Build Frontend
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build frontend docker image
        run: docker build -t hristijanalachoski/webapp-frontend ./frontend
      - name: Pushing docker image to Docker Hub
        run: docker push hristijanalachoski/webapp-frontend
  deploy-backend-dev:
    name: Deploy Backend to Kubernetes DEV
    runs-on: self-hosted
    needs: [build-backend]
    steps:
      - run: echo "Deploying Backend.."
  deploy-frontend-dev:
    name: Deploy Frontend to Kubernetes DEV
    runs-on: self-hosted
    needs: [build-frontend]
    steps:
      - run: echo "Deploying Frontend.."
  test-backend-dev:
    name: Run API Tests against DEV Backend
    runs-on: self-hosted
    needs: [deploy-backend-dev]
    steps:
      - run: echo "Running tests.."
  deploy-backend-stg:
    name: Deploy Backend to Kubernetes STG
    runs-on: self-hosted
    needs: [test-backend-dev]
    steps:
      - run: echo "Deploying Backend.."
  deploy-frontend-stg:
    name: Deploy Frontend to Kubernetes STG
    runs-on: self-hosted
    needs: [deploy-frontend-dev]
    steps:
      - run: echo "Deploying Frontend.."
  test-backend-stg:
    name: Run API Tests against STG Backend
    runs-on: self-hosted
    needs: [deploy-backend-stg]
    steps:
      - run: echo "Running tests.."
  deploy-backend-prd:
    name: Deploy Backend to Kubernetes PRD
    runs-on: self-hosted
    needs: [test-backend-stg]
    steps:
      - run: echo "Deploying Backend.."
  deploy-frontend-prd:
    name: Deploy Frontend to Kubernetes PRD
    runs-on: self-hosted
    needs: [deploy-frontend-stg]
    steps:
      - run: echo "Deploying Frontend.."
  test-backend-prd:
    name: Run API Tests against PRD Backend
    runs-on: self-hosted
    needs: [deploy-backend-prd]
    steps:
      - run: echo "Running tests.."